### ISSUE TITLE
http error 500 when trying to deploy an eclipse plugin with maven and tycho

### ISSUE THREAD

**Issue by MHerbst** [eclipse/packagedrone#103]
I have installed package-drone 0.14 on Ubuntu Linux from the apt repository. I am trying to deploy an Eclipse Plugin with the Maven and Tycho 0.26. 

First of all I see these warnings:
```
[INFO] Uploaded: http://10.0.0.4:8080/maven/28cdd633-110b-428e-b510-739d467a125c/de/dstg/test/de.dstg.test/1.0.0-SNAPSHOT/de.dstg.test-1.0.0-20170214.075057-1.pom (2 KB at 19.7 KB/sec)
[WARNING] Failed to upload SHA-1 checksum for C:\Users\mh\git\de.dstg.test\de.dstg.test\pom.xml: Upload checksum failed for http://10.0.0.4:8080/maven/28cdd633-110b-428e-b510-739d467a125c/de/dstg/test/de.dstg.test/1.0.0-SNAPSHOT/de.dstg.test-1.0.0-20170214.075057-1.pom.sha1 with status code 406
[WARNING] Failed to upload MD5 checksum for C:\Users\mh\git\de.dstg.test\de.dstg.test\pom.xml: Upload checksum failed for http://10.0.0.4:8080/maven/28cdd633-110b-428e-b510-739d467a125c/de/dstg/test/de.dstg.test/1.0.0-SNAPSHOT/de.dstg.test-1.0.0-20170214.075057-1.pom.md5 with status code 406
[INFO] Downloading: http://10.0.0.4:8080/maven/28cdd633-110b-428e-b510-739d467a125c/de/dstg/test/de.dstg.test/maven-metadata.xml

```

And it ends with the following message:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.5:deploy (default-deploy) on project de.dstg.test: Failed to deploy artifacts: Could not transfer artifact de.dstg.test:de.dstg.test:xml:p2metadata:1.0.0-20170214.074441-1 from/to pdrone.28cdd633-110b-428e-b510-739d467a125c (http://10.0.0.4:8080/maven/28cdd633-110b-428e-b510-739d467a125c): Failed to transfer http://10.0.0.4:8080/maven/28cdd633-110b-428e-b510-739d467a125c/de/dstg/test/de.dstg.test/1.0.0-SNAPSHOT/de.dstg.test-1.0.0-20170214.074441-1-p2metadata.xml. Error code 500, Server Error -> [Help 1]
```

In the Package Drone channel I can see the deployed artifact:
![image](https://cloud.githubusercontent.com/assets/616792/22919842/69c32f0e-f292-11e6-90ce-c46976bcf3df.png)

The package-dron log file shows the following messages:
```
430  [AddonManager/Watcher] WARN  o.e.p.addon.internal.Watcher - Start watching: /usr/lib/package-drone-server/instance/configuration/org.eclipse.osgi/89/data/addons
440527 [qtp1300886093-34] WARN  o.e.p.r.w.utils.ChannelCacheHandler - Unable to find channel cache entry: p2.repo:content.jar
440540 [qtp1300886093-35] WARN  o.e.p.r.w.utils.ChannelCacheHandler - Unable to find channel cache entry: p2.repo:content.xml
454410 [qtp1300886093-36] WARN  o.e.jetty.servlet.ServletHandler -
javax.servlet.ServletException: java.lang.RuntimeException: java.io.IOException: Duplicate parents detected: [923926de-aef7-49a9-a089-685fd22634d1, da389bdd-3c9e-43b6-bc54-16ed807ead38]
        at org.eclipse.packagedrone.repo.adapter.maven.internal.MavenServlet.doPut(MavenServlet.java:173) ~[org.eclipse.packagedrone.repo.adapter.maven_1.0.0.20160627-0821.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) ~[javax.servlet_3.1.0.v201410161800.jar:3.1.0]
        at org.eclipse.packagedrone.repo.channel.servlet.AbstractChannelServiceServlet.service(AbstractChannelServiceServlet.java:85) ~[org.eclipse.packagedrone.repo.channel_1.0.0.20160624-0921.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet_3.1.0.v201410161800.jar:3.1.0]

```

**Comment by ctron** [comment]
Hm ... so the issue here is that when uploading a secondary artifact, it cannot properly detect the parent artifact. You could try to add the "Tycho cleaner" and let Package Drone generate the metadata.
