### ISSUE TITLE
Invalid admin credentials on fresh install

### ISSUE THREAD

**Issue by jeandersonbc** [eclipse/packagedrone#35]
Hello everyone,

My Environment:
* Windows 10
* Eclipse IDE for Eclipse Committers
 * Version: Mars.1 Release (4.5.1)
 * Build id: 20150924-1200

I couldn't sign in on the system using the admin token **when I first started Package Drone**.

I checked the **console output** and **.drone-admin-token** file but I still get a "Login error! Invalid username or password".

In an attempt to figure what was going on, I checked Google Chrome Developer Tools to debug the POST request. However, the backend is returning status code 200 (Success):

![couldnt-login](https://cloud.githubusercontent.com/assets/2225536/13063915/74b684d8-d434-11e5-92f2-0eeaf2c49695.png)

Bug maybe? I'm going to look for the authentication entry-point on the backend to investigate this.

**Comment by ctron** [comment]
I never saw that, so maybe it is something Windows related. Although I do know that the integration tests ran fine on Windows 7.

**Comment by jeandersonbc** [comment]
I tried to run TestSuite to see what tests can tell me about the Login functionality but I didn't have much success:

```{java}
java.nio.file.NoSuchFileException: target\instance\plugins
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
	at java.nio.file.Files.walk(Files.java:3574)
	at java.nio.file.Files.walk(Files.java:3625)
	at org.eclipse.packagedrone.testing.server.ServerRunner.findLauncher(ServerRunner.java:89)
	at org.eclipse.packagedrone.testing.server.ServerRunner.start(ServerRunner.java:66)
	at org.eclipse.packagedrone.testing.server.TestSuite.startServer(TestSuite.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
Seems like the `findLaucher` is supposed to return the Equinox Launcher path but it doesn't find any jar on the indicated file.

Looks like I'm missing some step before running the package drone suite.
Is there any prior step before running drone tests? I don't think this specific issue is related to OS because indeed I didn't find any /target/instance/plugins path.

Any suggestions?

**Comment by jeandersonbc** [comment]
@ctron I don't know if Jetty version would affect this or not but I just updated my project and tried again to sign in.... Now it is working normally, although I had that issue running TestSuite but now it's a non-related problem.

Maybe you should close this issue.

**Comment by ctron** [comment]
You will need to run the nan build before running the integration test. This could be done by a maven dependency, but then again this would cause some more trouble by having the requirement to deploy the full build to the local repository each time.

**Comment by ctron** [comment]
Ok, I'll do so. I guess we can reopen it otherwise.
