### ISSUE TITLE
Error Performing Launch runtime/runtime build.ant.launch

### ISSUE THREAD

**Issue by ianaykh** [eclipse/packagedrone#45]
java.lang.Exception: No launcher found for runtime/runtime build.ant.launch
  at org.eclipse.oomph.setup.launching.impl.LaunchTaskImpl.perform(LaunchTaskImpl.java:260)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3036)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2980)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4170)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4164)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4162)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2971)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2946)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2857)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:555)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:674)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by ctron** [comment]
Could you please give me the last few steps which lead to this issue.

**Comment by ianaykh** [comment]
Hi Ctron, this is the entire error log which appears during startup setup.

`Executing startup tasks
Product org.eclipse.products.epp.package.jee.mars
Project org.eclipse.packagedrone.master
Bundle org.eclipse.oomph.setup 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Bundle org.eclipse.oomph.setup.core 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Bundle org.eclipse.oomph.setup.git 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Bundle org.eclipse.oomph.setup.jdt 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Bundle org.eclipse.oomph.setup.launching 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Bundle org.eclipse.oomph.setup.p2 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Bundle org.eclipse.oomph.setup.pde 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Bundle org.eclipse.oomph.setup.projects 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Bundle org.eclipse.oomph.setup.targlets 1.3.0.v20160213-0953, build=2199, branch=7194e06d06a87ced95779121a8281b59b9abdf81, commit=7194e06d06a87ced95779121a8281b59b9abdf81
Performing Preference compiler.annotation.nullanalysis = enabled
Performing Preference compiler.problem.nullReference = error
Performing Preference compiler.problem.potentialNullReference = error
Performing Launch runtime/runtime build.ant.launch
java.lang.Exception: No launcher found for runtime/runtime build.ant.launch
  at org.eclipse.oomph.setup.launching.impl.LaunchTaskImpl.perform(LaunchTaskImpl.java:260)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3036)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2980)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4170)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4164)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4162)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2971)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2946)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2857)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:555)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:674)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Took 0 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
`

**Comment by ctron** [comment]
Ok, I'll give it a look.

**Comment by addiittya2006** [comment]
Can this be reproduced on a Fresh Install?
Where did you clone the repo from, Is it complete?

**Comment by ctron** [comment]
Closing until there is more information.
