### ISSUE TITLE
Error while uploading category.xml

### ISSUE THREAD

**Issue by ctron** [eclipse/packagedrone#6]
Originally opened issue: ctron/package-drone#142 by @SvenEwald

Uploading a `category.xml` with the "P2 Category Generator (XML)" fails with an exception:

```
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    at org.eclipse.packagedrone.repo.XmlHelper.parse(XmlHelper.java:204)
    at org.eclipse.packagedrone.repo.generator.p2.xml.CategoryXmlGenerator.generate(CategoryXmlGenerator.java:50)
    at org.eclipse.packagedrone.repo.generator.GeneratorProcessor.lambda$0(GeneratorProcessor.java:77)
    ... 119 more
```

**Comment by ctron** [comment]
The cause for this is that the uploading web ui controller provides an empty array instead of the actual uploaded BLOB stream.
