### ISSUE TITLE
Return code 500 when uploading large zip

### ISSUE THREAD

**Issue by berryma4** [eclipse/packagedrone#73]
I attempted to upload eclipse 4.5 (~2.5GB zipped) as a zip file using mvn deploy:deploy-file.
Received error: Return code is 500, ReasonPhrase: Server Error.

Using Package Drone version 0.13.0.20160504-0926 on Debian Jessie.

I did not have any issues with the eclipse 4.5 update site (~691MB zipped)

**Comment by ctron** [comment]
Could you please provide the stack trace from the log file. Otherwise it is hard to tell what went wrong.

**Comment by berryma4** [comment]
```
!SESSION 2016-06-23 08:48:53.526 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -consoleLog

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-23 08:48:59.364
!MESSAGE Could not bind a reference of component org.eclipse.packagedrone.repo.manage.system.sitePrefix. The reference is: Reference[name = CoreService, interface = org.eclipse.packagedrone.repo.manage.core.CoreService, policy = dynamic, cardinality = 0..1, target = null, bind = setCoreService, unbind = unsetCoreService]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-23 08:48:59.386
!MESSAGE Could not bind a reference of component org.eclipse.packagedrone.repo.manage.system.service. The reference is: Reference[name = Server, interface = org.eclipse.jetty.server.Server, policy = dynamic, cardinality = 0..1, target = null, bind = setServer, unbind = unsetServer]

!ENTRY org.eclipse.packagedrone.storage.apm.config 4 0 2016-06-23 08:49:00.100
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.packagedrone.storage.apm.config.Activator.start() of bundle org.eclipse.packagedrone.storage.apm.config.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.eclipse.packagedrone.storage.apm.StorageManager.validateBasePath(StorageManager.java:318)
	at org.eclipse.packagedrone.storage.apm.StorageManager.<init>(StorageManager.java:296)
	at org.eclipse.packagedrone.storage.apm.config.Activator.registerWithPath(Activator.java:101)
	at org.eclipse.packagedrone.storage.apm.config.Activator.start(Activator.java:49)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	... 12 more
Root exception:
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.eclipse.packagedrone.storage.apm.StorageManager.validateBasePath(StorageManager.java:318)
	at org.eclipse.packagedrone.storage.apm.StorageManager.<init>(StorageManager.java:296)
	at org.eclipse.packagedrone.storage.apm.config.Activator.registerWithPath(Activator.java:101)
	at org.eclipse.packagedrone.storage.apm.config.Activator.start(Activator.java:49)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.osgi 4 0 2016-06-23 08:49:00.564
!MESSAGE Bundle org.eclipse.packagedrone.storage.apm.config_1.0.0.20151104-1838 [149] is not active.

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-23 08:49:01.670
!MESSAGE Could not bind a reference of component org.eclipse.packagedrone.mail.web.task. The reference is: Reference[name = MailService, interface = org.eclipse.packagedrone.mail.MailService, policy = dynamic, cardinality = 0..1, target = null, bind = setService, unbind = unsetService]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-23 08:49:01.766
!MESSAGE Could not bind a reference of component org.eclipse.packagedrone.repo.manage.setup.web.setup. The reference is: Reference[name = StorageManager, interface = org.eclipse.packagedrone.storage.apm.StorageManager, policy = dynamic, cardinality = 0..1, target = null, bind = setService, unbind = unsetService]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-23 08:49:01.774
!MESSAGE Could not bind a reference of component org.eclipse.packagedrone.repo.manage.system.web.info. The reference is: Reference[name = StorageManager, interface = org.eclipse.packagedrone.storage.apm.StorageManager, policy = dynamic, cardinality = 0..1, target = null, bind = setManager, unbind = unsetManager]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-23 08:49:01.880
!MESSAGE Could not bind a reference of component org.eclipse.packagedrone.sec.service.common.secMail. The reference is: Reference[name = MailService, interface = org.eclipse.packagedrone.mail.MailService, policy = dynamic, cardinality = 0..1, target = null, bind = setMailService, unbind = unsetMailService]

!ENTRY org.eclipse.equinox.ds 1 0 2016-06-23 08:49:01.902
!MESSAGE Could not bind a reference of component org.eclipse.packagedrone.mail.web.config. The reference is: Reference[name = DefaultMailService, interface = org.eclipse.packagedrone.mail.java.DefaultMailService, policy = dynamic, cardinality = 0..1, target = null, bind = setMailService, unbind = unsetMailService]
```

**Comment by berryma4** [comment]
I'm sorry, I don't see anything in the configuration/{timstanp}.log files.

**Comment by berryma4** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:
deploy-file (default-cli) on project eclipse-dependencies: Failed to deploy arti
facts: Could not transfer artifact org.csstudio:eclipse:zip:4.5 from/to controls
 (http://xxx:8080/maven/eclipse-4.5): Failed to transfer file: http:
//xxx:8080/maven/eclipse-4.5/org/csstudio/eclipse/4.5/eclipse-4.5.zi
p. Return code is: 500, ReasonPhrase: Server Error. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
```

**Comment by ctron** [comment]
Which way are you starting Server? When using Upstart there is a log in the upstart log folder. Otherwise you may need to adapt the "logback" configuration.

**Comment by cleanerx** [comment]
I suppose the problem is the same as
https://github.com/ctron/package-drone/issues/147
Add system properties through -D
osgi.web.dispatcher.multipart.maxFileSize=<yoursize>
osgi.web.dispatcher.multipart.maxRequestSize=<yoursize>

**Comment by berryma4** [comment]
Thank you!  Yes, this sounds to be a duplicate.  I'll close the issue with the system properties solving the problem.
